name: Android CI

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
      
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.1.0
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    - name: Run Unit Tests
      run: bash ./gradlew test --stacktrace
      
  ktlint:

    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2.1.0
      - name: set up JDK 1.8
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      - name: Run Ktlint Check
        run: ./gradlew ktlintCheck
      - name: Run Ktlint Format
        run: ./gradlew ktlintFormat
    
    
